spring:
  application:
    name: thejoo-service-main
  datasource:
    username: ${MAIN_SERVICE_DATABASE_USER}
    password: ${MAIN_SERVICE_DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        types.print.banner: false

  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  error:
    include-stacktrace: NEVER
  port: 8080
springdoc:
  swagger-ui:
    path: /doc
    tags-sorter: alpha
    operations-sorter: alpha
    supported-submit-methods: []
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
logging.level:
    org.hibernate.SQL: DEBUG
token:
  default-issuer: ${spring.application.name}-${spring.profiles.active}
  default-audience: ${spring.application.name}-${spring.profiles.active}
  keystore:
    type: JKS
    filename: thejoo-keystore-${spring.profiles.active}.jks
    password: ${MAIN_SERVICE_KEYSTORE_PASSWORD}
  properties:
    auth:
      alias: thejoo-auth-leaf
      password: ${token.keystore.password}
      issuer: ${token.default-issuer}
      audience: ${token.default-audience}
    user-read:
      alias: thejoo-user-qr-leaf
      password: ${token.keystore.password}
      issuer: ${token.default-issuer}
      audience: ${token.default-audience}
    promotion:
      alias: thejoo-promotion-leaf
      password: ${token.keystore.password}
      audience: ${token.default-audience}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/thejoo_dev
    username: thejoo_dev_admin
    password: Admin123Admin123
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
        default_schema: thejoo_main
token:
  keystore:
    password: Admin123Admin123
  properties:
    auth:
      duration: PT3H
    user-read:
      duration: PT15M
    promotion:
      duration: PT15M

---

spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    url: jdbc:postgresql://thejoo-dev.csmjwfz4i4c8.ap-northeast-2.rds.amazonaws.com/thejoo
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
        default_schema: thejoo_main_sandbox
token:
  properties:
    auth:
      duration: PT30M
    user-read:
      duration: PT5M
    promotion:
      duration: PT5M